apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP     
  selector:
    app: backend 
  ports:
  - name: flask
    port: 5001
    targetPort: 5001
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: htrvolker/python-backend:letters
        ports:
          - containerPort: 5001